### ISSUE TITLE
Follow practises for Better Code Quality

### ISSUE THREAD

**Issue by AdityaGupta150** [AdityaGupta150/Ludo-The_Game#18]
Though the repo maintains great standards according to automated review systems, but since there is always a scope to be better... codefactor.io gives a C rating to the repo, due to the complexity of code at particular files, so that is a great way to improve the code, as well as know what practises are recommended and what not, since as you go solving even a few suggestions from there, you will gain a lot 👍🏽 .

Follow the suggestions from these review sites-
[CodeFactor](https://www.codefactor.io/repository/github/adityagupta150/ludo-the_game)
[Codacy](https://app.codacy.com/manual/AdityaGupta150/Ludo-The_Game/issues)

![Screenshot (8)](https://user-images.githubusercontent.com/37269665/94062498-62416a80-fe04-11ea-9c8b-b2700f5123a0.png)

**Comment by abraham-john-paul** [comment]
Hi, is this to fix the issued reported in codefactor?

**Comment by AdityaGupta150** [comment]
> 
> 
> Hi, is this to fix the issued reported in codefactor?

Yes, the issue is regarding the issues raised by codefactor. Though you can also suggest a change that you believe will be better for that piece of code. 😃

**Comment by AdityaGupta150** [comment]
#20 fixed many redundant blank lines and unused variable issues.

Now mainly, you can work on reducing the complexity of the functions, even if a bit, i appreciate it, the issue will remain open, maybe till Hacktoberfest ends, since code quality can always be better 😄 , in the meantime i will also be working to make them better to work for you, so rebase your code before PR 👍🏽 .

**Comment by abraham-john-paul** [comment]
Hey, while running the pgm, and we enter player names, after 4 players it goes back to player 1.
in in game::takeIntro() in game.cpp; 
the util_lamdas::nextPlayer(p), always sets it back to player1, so, i cant proceed from this screen

**Comment by abraham-john-paul** [comment]
As an improvement, in 
bool game::InitGame(short playerConsent) in game.cpp
the loop
`for( size_t r = 0; r < board.size(); ++r ){
			for( size_t c = 0; c < board.at(r).size(); ++c ){
				board[r][c].content.clear();
				board[r][c].inBoxGotis.clear();
			}
		}`
can be changed to a range based for loop for better readability

**Comment by AdityaGupta150** [comment]
> 
> 
> Hey, while running the pgm, and we enter player names, after 4 players it goes back to player 1.
> in in game::takeIntro() in game.cpp;
> the util_lamdas::nextPlayer(p), always sets it back to player1, so, i cant proceed from this screen

Yes, that had been fixed in the dev branch, maybe i forgot to merge them. 😅
It had been changed to a for loop, from 0 to 4, so a maximum of 4 players input. The problem came due to the change here - 
https://github.com/AdityaGupta150/Ludo-The_Game/blob/589e213a5b626fdd43a97aec84df4922cb80d638/src/game.cpp#L478-L479



> 
> 
> As an improvement, in
> bool game::InitGame(short playerConsent) in game.cpp
> the loop
> `for( size_t r = 0; r < board.size(); ++r ){ for( size_t c = 0; c < board.at(r).size(); ++c ){ board[r][c].content.clear(); board[r][c].inBoxGotis.clear(); } }`
> can be changed to a range based for loop for better readability

Yes, i saw now it can be converted to a range based for, and prefer auto& for that. Willing to improve it yourself ?

**Comment by abraham-john-paul** [comment]
Yes
can i send PR after Oct 1st?

**Comment by AdityaGupta150** [comment]
> 
> 
> Yes
> can i send PR after Oct 1st?

Yes, it was actually meant for Hacktoberfest contributions nevertheless. Try to be productive in whatever you chose to contribute 👍🏽 .

**Comment by meghagoyal04** [comment]
Hey! Can I send a PR during the hacktober fest?

**Comment by AdityaGupta150** [comment]
Yes, you can contribute 🎉 

> 
> 
> Hey! Can I send a PR during the hacktober fest?

**Comment by AdityaGupta150** [comment]
> Note- The PR is still open, but may not be as simple as removing whitespaces now, but you can attempt improving small pieces of code too 🎉 \

**Comment by AdityaGupta150** [comment]
@meghagoyal04  Have a look at this - 

![Screenshot_2020-10-01 AdityaGupta150 Ludo-The_Game - Active alerts - LGTM](https://user-images.githubusercontent.com/37269665/94772094-7d007a00-03d6-11eb-885e-136bac881d3c.png)

This is a review by lgtm, it is pretty staightforward, as well as a chance to improve real code and know more code practises ⚡ 

Anyone who comes here can also take up this issue 👍🏽
